{
 "title": "Weka Cluster Overview",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Filter" }
  ]
 },
 "panels": [
  { "title": "Cluster Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster Name and Weka version",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 11, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "weka_info",
     "legendFormat": "Cluster: {{cluster}}, Version: {{version}}"
    }
   ]
  },
  {
   "title": "Cluster Total Capacity",
   "type": "singlestat",
   "description": "Total capacity of the cluster",
   "gridPos": { "h": 5, "w": 4, "x": 11, "y": 1 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    { "expr": "weka_drive_storage_total_bytes" }
   ]
  },
  {
   "title": "Cluster Available Unprovisioned Capacity",
   "type": "singlestat",
   "description": "Capacity that has not been put into a filesystem",
   "gridPos": { "h": 5, "w": 4, "x": 15, "y": 1 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "weka_drive_storage_unprovisioned_bytes"
    }
   ]
  },
  {
   "title": "Weka Uptime Days",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "weka_uptime", "legendFormat": "{{cluster}}" }
   ]
  },
  {
   "title": "Protection Status",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 6, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "weka_protection", "legendFormat": "{{numFailures}} Failures" }
   ]
  },
  {
   "title": "Cluster Used Capacity",
   "type": "graph",
   "description": "Total Used drive capacity",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "weka_drive_storage_total_bytes - weka_drive_storage_unprovisioned_bytes",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Cluster Status",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "weka_info",
     "legendFormat": "Cluster IO Status: {{io_status}}, License Status: {{license_status}}, Link Layer: {{link_layer}}"
    }
   ]
  },
  {
   "title": "Weka Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 7, "y": 7 },
   "format": "none",
   "valueName": "name",
   "targets": [
    { "expr": "weka_status", "legendFormat": "Status: {{status}}" }
   ]
  },
  {
   "title": "System Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current Throughput",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (weka_THROUGHPUT_bytespersec)",
       "legendFormat": "{{cluster}}"
      }
     ]
    },
    {
     "title": "Avg Throughput",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 8, "x": 9, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum (weka_THROUGHPUT_bytespersec)",
       "legendFormat": "{{cluster}}"
      }
     ]
    },
    {
     "title": "Max Throughput",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 7, "x": 17, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum (weka_THROUGHPUT_bytespersec)",
       "legendFormat": "{{cluster}}"
      }
     ]
    }
   ]
  },
  { "title": "Cluster Filesystem Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "FS Total Used Capacity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "weka_fs_used_bytes", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Weka Filesystem sizes",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "weka_fs_size_bytes", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "FS Capacity Utilization %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "weka_fs_utilization_percent", "legendFormat": "{{fsname}}" }
   ]
  },
  {
   "title": "FS Total Used Capacity % Prediction next 30 days based on prev 30 days",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "abs(predict_linear(weka_fs_utilization_percent[30d], 86400*30)) < 100",
     "legendFormat": "{{fsname}}"
    }
   ]
  },
  { "title": "Cluster CPU Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Weka FE Core Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg by (host_name) (weka_stats{stat=\"CPU_UTILIZATION\",node_role=\"FRONTEND\"})",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "Weka Drives Core Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 31 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg by (host_name) (weka_stats{stat=\"CPU_UTILIZATION\",node_role=\"DRIVES\"})",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "Weka Compute Core Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 6, "y": 39 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg by (host_name) (weka_stats{stat=\"CPU_UTILIZATION\",node_role=\"COMPUTE\"})",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  { "title": "Cluster-wide IO Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Operations per second, total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    { "expr": "weka_overview_activity_ops", "legendFormat": "{{cluster}}" }
   ]
  },
  {
   "title": "Throughput per second, total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "weka_overview_activity_read_bytespersec + weka_overview_activity_write_bytespersec",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Read vs Write IOPS, total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "weka_overview_activity_write_iops",
     "legendFormat": "writes"
    },
    {
     "expr": "weka_overview_activity_read_iops",
     "legendFormat": "reads"
    }
   ]
  },
  {
   "title": "Read vs Write Bytes per second, total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "weka_overview_activity_read_bytespersec",
     "legendFormat": "reads"
    },
    {
     "expr": "weka_overview_activity_write_bytespersec",
     "legendFormat": "writes"
    }
   ]
  },
  {
   "title": "Metadata, total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "weka_overview_activity_ops - weka_overview_activity_write_iops - weka_overview_activity_read_iops",
     "legendFormat": "metadata ops"
    }
   ]
  },
  {
   "title": "Download vs Upload Object Store Data Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "weka_overview_activity_object_download_bytespersec",
     "legendFormat": "download"
    },
    {
     "expr": "weka_overview_activity_object_upload_bytespersec",
     "legendFormat": "upload"
    }
   ]
  },
  { "title": "Cluster IO Statistcs by Host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "Reads per second by host",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "sum by (host_name) (weka_stats{category=\"ops\",stat=\"READS\"})",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "Writes per second by host",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "sum by (host_name) (weka_stats{category=\"ops\",stat=\"WRITES\"})",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "Operations per second by host",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "sum by (host_name) (weka_stats{category=\"ops\",stat=\"OPS\"})",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "Total Throughput per second by host",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (host_name) (weka_stats{category=\"ops\",stat=\"THROUGHPUT\"})",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "Read Bytes per second by host",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (host_name) (weka_stats{category=\"ops\",stat=\"READ_BYTES\"})",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "Write Bytes per second by host",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 89 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (host_name) (weka_stats{category=\"ops\",stat=\"WRITE_BYTES\"})",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "Metadata ops by host",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 97 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (host_name) ( weka_stats{category=\"ops\",stat=\"OPS\"} ) - sum by (host_name)( weka_stats{category=\"ops\",stat=\"READS\"} )- sum by (host_name)( weka_stats{category=\"ops\",stat=\"WRITES\"} )",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "Total IO Latency by host",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 97 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "avg by (host_name) (weka_stats{category=\"ops\",stat=\"READ_LATENCY\"})",
     "legendFormat": "{{host_name}} read"
    },
    {
     "expr": "avg by (host_name) (weka_stats{category=\"ops\",stat=\"WRITE_LATENCY\"})",
     "legendFormat": "{{host_name}} write"
    }
   ]
  },
  { "title": "Top Clients", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 105 } },
  {
   "title": "Top 5 Clients by IOPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 106 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "topk( 5, sum by (host_name) (weka_stats{category=\"ops\",stat=\"READS\",host_role=\"client\"}) + sum by (host_name) (weka_stats{category=\"ops\",stat=\"WRITES\",host_role=\"client\"}))  ",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "Top 5 Clients by Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 106 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "topk( 5, sum by (host_name) (weka_stats{category=\"ops\",stat=\"THROUGHPUT\",host_role=\"client\"}))",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "Top 5 Clients by Read Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 114 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "topk( 5, sum by (host_name) (weka_stats{category=\"ops\",stat=\"READ_LATENCY\",host_role=\"client\"}))",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "Top 5 Clients by Write Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 114 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "topk( 5, sum by (host_name) (weka_stats{category=\"ops\",stat=\"WRITE_LATENCY\",host_role=\"client\"}))",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "Top 5 Clients by write bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 122 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "topk( 5, sum by (host_name) (weka_stats{category=\"ops\",stat=\"WRITE_BYTES\",host_role=\"client\"}))",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "Top 5 Clients by read bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 122 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "topk( 5, sum by (host_name) (weka_stats{category=\"ops\",stat=\"READ_BYTES\",host_role=\"client\"}))",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "Top 5 Clients by Metadata Ops",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 5, "y": 130 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "topk( 5, sum by (host_name) (weka_stats{category=\"ops\",stat=\"OPS\",host_role=\"client\"}) - sum by (host_name) (weka_stats{category=\"ops\",stat=\"READS\",host_role=\"client\"}) - sum by (host_name) (weka_stats{category=\"ops\",stat=\"WRITES\",host_role=\"client\"}))",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  { "title": "per core stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 138 } },
  {
   "title": "CPU Utilization by NodeId/Core",
   "type": "graph",
   "gridPos": { "h": 14, "w": 22, "x": 0, "y": 139 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "weka_stats{category=\"cpu\",stat=\"CPU_UTILIZATION\"}",
     "legendFormat": "{{node_id}} {{host_name}} {{node_role}}"
    }
   ]
  }
 ]
}