{
 "title": "Weka Server/Client Detail",
 "description": "Weka Server/Client Details",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Filter" }
  ]
 },
 "panels": [
  { "title": "Client Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Client OPS",
   "type": "graph",
   "description": "Total Operations (io and metadata)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum (weka_stats{category=\"ops\",stat=\"OPS\"})",
     "legendFormat": "Operations per sec"
    }
   ]
  },
  {
   "title": "Total Client Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (weka_stats{category=\"ops\",stat=\"THROUGHPUT\"})",
     "legendFormat": "throughput"
    }
   ]
  },
  {
   "title": "OPS Details",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum (weka_stats{category=\"ops\",stat=\"READS\"})",
     "legendFormat": "reads"
    },
    {
     "expr": "sum (weka_stats{category=\"ops\",stat=\"WRITES\"})",
     "legendFormat": "writes"
    },
    {
     "expr": "sum (weka_stats{category=\"ops\",stat=\"OPS\"}) - sum (weka_stats{category=\"ops\",stat=\"READS\"}) - sum(weka_stats{category=\"ops\",stat=\"WRITES\"})",
     "legendFormat": "metadata ops"
    }
   ]
  },
  {
   "title": "Throughput Details",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (weka_stats{category=\"ops\",stat=\"READ_BYTES\"})",
     "legendFormat": "read bytes"
    },
    {
     "expr": "sum (weka_stats{category=\"ops\",stat=\"WRITE_BYTES\"})",
     "legendFormat": "write bytes"
    }
   ]
  },
  {
   "title": "Average Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "avg (weka_stats{category=\"ops\",stat=\"READ_LATENCY\"})",
     "legendFormat": "read latency"
    },
    {
     "expr": "avg (weka_stats{category=\"ops\",stat=\"WRITE_LATENCY\"})",
     "legendFormat": "write latency"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg (weka_stats{category=\"cpu\",stat=\"CPU_UTILIZATION\"})",
     "legendFormat": "% CPU"
    }
   ]
  },
  { "title": "Per Node Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Read Ops Details",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "weka_stats{category=\"ops\",stat=\"READS\"}",
     "legendFormat": "{{node_id}} reads"
    }
   ]
  },
  {
   "title": "Write OPS Details",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "weka_stats{category=\"ops\",stat=\"WRITES\"}",
     "legendFormat": "{{node_id}} writes"
    }
   ]
  },
  {
   "title": "Read Throughput Details",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "weka_stats{category=\"ops\",stat=\"READ_BYTES\"}",
     "legendFormat": "{{node_id}} reads"
    }
   ]
  },
  {
   "title": "Write Throughput Details",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "weka_stats{category=\"ops\",stat=\"WRITE_BYTES\"}",
     "legendFormat": "{{node_id}} writes"
    }
   ]
  },
  {
   "title": "Read Latency Details",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "weka_stats{category=\"ops\",stat=\"READ_LATENCY\"}",
     "legendFormat": "{{node_id}} reads"
    }
   ]
  },
  {
   "title": "Write Latency Details",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "weka_stats{category=\"ops\",stat=\"WRITE_LATENCY\"}",
     "legendFormat": "{{node_id}} writes"
    }
   ]
  },
  {
   "title": "Metadata OPS Details",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (node_id) ( weka_stats{category=\"ops\",stat=\"OPS\"} ) - sum by (node_id)( weka_stats{category=\"ops\",stat=\"READS\"} )- sum by (node_id)( weka_stats{category=\"ops\",stat=\"WRITES\"} )",
     "legendFormat": "{{node_id}} metadata ops"
    }
   ]
  },
  {
   "title": "Cpu Utilization Details",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "weka_stats{category=\"cpu\",stat=\"CPU_UTILIZATION\"}",
     "legendFormat": "{{node_id}} {{node_role}}"
    }
   ]
  }
 ]
}