{
 "title": "Weka Realtime",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Filter" }
  ]
 },
 "panels": [
  {
   "title": "Operations per sec by host",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (host_name) (weka_realtime_stats{stat=\"ops_per_second\"})",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "Read/Write per sec by host",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (host_name) (weka_realtime_stats{stat=\"reads_per_second\"})",
     "legendFormat": "{{host_name}} reads"
    },
    {
     "expr": "sum by (host_name) (weka_realtime_stats{stat=\"writes_per_second\"})",
     "legendFormat": "{{host_name}} writes"
    }
   ]
  },
  {
   "title": "CPU Utilization by host",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg by (host_name) (weka_realtime_stats{stat=\"cpu_utilization_percentage\"})",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "Read/Write Latency by host",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "avg by (host_name) (weka_realtime_stats{stat=\"read_latency_usecs\"})",
     "legendFormat": "{{host_name}} read"
    },
    {
     "expr": "avg by (host_name) (weka_realtime_stats{stat=\"write_latency_usecs\"})",
     "legendFormat": "{{host_name}} write"
    }
   ]
  },
  {
   "title": "CPU Utilization by node",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "weka_realtime_stats{stat=\"cpu_utilization_percentage\"}",
     "legendFormat": "{{host_name}} {{node_id}} {{node_role}}"
    }
   ]
  },
  {
   "title": "Network Bytes/Sec by host",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "avg by (host_name) (weka_realtime_stats{stat=\"L6RX_bytes_per_second\"})",
     "legendFormat": "{{host_name}} receive"
    },
    {
     "expr": "avg by (host_name) (weka_realtime_stats{stat=\"L6TX_bytes_per_second\"})",
     "legendFormat": "{{host_name}} transmit"
    }
   ]
  },
  {
   "title": "Object Store Bytes Per Sec by host",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (host_name) (weka_realtime_stats{stat=\"obs_download_bytes_per_second\"})",
     "legendFormat": "{{host_name}} download"
    },
    {
     "expr": "sum by (host_name) (weka_realtime_stats{stat=\"obs_upload_bytes_per_second\"})",
     "legendFormat": "{{host_name}} upload"
    }
   ]
  }
 ]
}